# Generated by Django 3.1.5 on 2021-02-11 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_cart_app', '0003_auto_20210211_1613'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',), 'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
    ]
