# Generated by Django 3.1.7 on 2021-03-04 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_cart_app', '0004_auto_20210211_1518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='desc',
        ),
    ]
